server:
  port: 8080
spring:
  application:
    name: example-spring-boot-web-simple
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: "*"